version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /appdata/jellyfin/config:/config
      - /appdata/jellyfin/cache:/cache
      - /mnt/media/drive/videos:/data/media
      - /mnt/media/etc:/data/etc
      - /mnt/media/drive/videos/downloads:/data/downloads
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      # VAAPI Devices (examples)
      - /dev/dri:/dev/dri
    restart: unless-stopped