- name: Mount the drives
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: ext4
    opts: noatime,defaults,nofail
    passno: 2
    state: mounted
  with_items:
    - src: "LABEL=black"
      path: "/mnt/disk1"
    - src: "LABEL=nvme_old"
      path: "/mnt/disk2"
    - src: "LABEL=t5"
      path: "/mnt/disk3"

    - src: "LABEL=book"
      path: "/mnt/media"
    - src: "LABEL=other"
      path: "/mnt/others"
    - src: "LABEL=4tb"
      path: "/mnt/backup"
