- name: Mount the drives
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: ext4
    opts: noatime,defaults,nofail
    passno: 2
    state: mounted
  with_items:
    - src: "UUID=5677c4eb-3e6b-433c-982f-84ba5a5815a8"
      path: "/mnt/disk1"
    - src: "UUID=17d620e1-3fbd-477c-ba2e-8a6cf2fc8163"
      path: "/mnt/disk2"
    - src: "UUID=5c887ede-c5f8-4b56-a0e4-1156c34e7b27"
      path: "/mnt/media"
    - src: "UUID=ce7f0de4-f1e4-4e4b-a60b-826dd12cf947"
      path: "/mnt/others"
    - src: "UUID=696497b9-d3d6-4fbd-96dc-b4279afbc5da"
      path: "/mnt/backup"
    # - src: "UUID=61815d08-86a6-4c46-baeb-f9c73f2ba905"
    #   path: "/mnt/disk3"
