version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=<CLOUDFLARE_API_KEY>
      - ZONE=vsoni.com
      - SUBDOMAIN=connect
      - PROXIED=false